### ISSUE TITLE
Is there StatsD on this docker?

### ISSUE THREAD

**Issue by gblmarquez** [kamon-io/docker-grafana-influxdb#14]
Hi Guys,

I just cloned the repo and started using but I think there is no statsd on the docker, Am I wrong?

Best regards,
Gabriel Marquez

**Comment by dpsoft** [comment]
@gblmarquez there is not statsd server in this repo.

**Comment by gblmarquez** [comment]
Thanks @dpsoft for the reply. 

May I ask you to change the repository description? 
Docker image with InfluxDB, Grafana and a Kamon Dashboard
