### ISSUE TITLE
Issue when running start script on OS X using boot2docker

### ISSUE THREAD

**Issue by mrafayaleem** [kamon-io/docker-grafana-influxdb#6]
When running this container using the provided start script under boot2docker on Mac OS X, you would get something like the following:
```bash
a4d3e7677c8337f3b56f2c1970e7745adcbcc4334445a976d45c64b00aa7160e 2014/09/05 18:22:31 Error response from daemon: Cannot start container a4d3e7677c8337f3b56f2c1970e7745adcbcc4334445a976d45c64b00aa7160e: setup mount namespace bind mounts mounting /etc/localtime into /mnt/sda1/var/lib/docker/aufs/mnt/a4d3e7677c8337f3b56f2c1970e7745adcbcc4334445a976d45c64b00aa7160e/etc/localtime not a directory
```

This issue was discussed [here](https://github.com/boot2docker/boot2docker/issues/290) and [here](http://stackoverflow.com/a/26454059/569085). To bypass this issue and successfully boot a docker container using boot2docker, use the following instead of the one in the start script:
```bash
docker run -d -p 80:80 -p 8083:8083 -p 8084:8084 -p 8086:8086 --name grafana-influxdb_con grafana_influxdb
```

**Comment by ivantopo** [comment]
Solved by #7.
